import type { LucideIcon } from 'lucide-react-native';
import {
  Baby,
  Bell,
  Bike,
  BookOpen,
  Briefcase,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Cat,
  Clock,
  Code,
  Coffee,
  CreditCard,
  Dog,
  Dumbbell,
  Film,
  Flag,
  Gamepad2,
  GraduationCap,
  Heart,
  House,
  ListTodo,
  Mail,
  MapPin,
  MessageCircle,
  Moon,
  Music,
  Palette,
  Pencil,
  Phone,
  Pill,
  Plane,
  ShoppingCart,
  Star,
  Stethoscope,
  Sun,
  Target,
  TreePine,
  Trophy,
  Umbrella,
  User,
  Utensils,
  Wallet,
  Wrench,
} from 'lucide-react-native';

// Curated subset (SPEC.md §6 / DESIGN.md §5) — not the full ~1,600-icon library.
// Keys are the canonical Lucide kebab-case name, stored verbatim on tasks and
// categories, so this map is the single place a rename has to be reconciled.
export const ICONS: Record<string, LucideIcon> = {
  'list-todo': ListTodo,
  user: User,
  briefcase: Briefcase,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  clock: Clock,
  house: House,
  heart: Heart,
  dumbbell: Dumbbell,
  coffee: Coffee,
  utensils: Utensils,
  'shopping-cart': ShoppingCart,
  plane: Plane,
  car: Car,
  bike: Bike,
  wallet: Wallet,
  'credit-card': CreditCard,
  phone: Phone,
  mail: Mail,
  'message-circle': MessageCircle,
  music: Music,
  palette: Palette,
  code: Code,
  pill: Pill,
  stethoscope: Stethoscope,
  dog: Dog,
  cat: Cat,
  baby: Baby,
  star: Star,
  flag: Flag,
  bell: Bell,
  pencil: Pencil,
  camera: Camera,
  film: Film,
  'gamepad-2': Gamepad2,
  'tree-pine': TreePine,
  sun: Sun,
  moon: Moon,
  umbrella: Umbrella,
  wrench: Wrench,
  target: Target,
  trophy: Trophy,
  'map-pin': MapPin,
};

export const ICON_NAMES = Object.keys(ICONS);

export function getIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return ICONS[name] ?? null;
}
